# Generated by Django 5.0.4 on 2024-05-13 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('status', models.IntegerField(choices=[(0, 'Dead'), (1, 'Alive'), (2, 'Unknown')])),
                ('species', models.IntegerField(choices=[(0, 'Human'), (1, 'Alien'), (2, 'Mythological'), (3, 'Unknown'), (4, 'Animal'), (5, 'Disease'), (6, 'Robot'), (7, 'Croneberg')])),
                ('type', models.CharField(max_length=255)),
                ('gender', models.IntegerField(choices=[(0, 'Female'), (1, 'Male'), (2, 'Genderless'), (3, 'Unknown')])),
                ('image', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('created', models.DateTimeField()),
            ],
            options={
                'db_table': 'characters',
            },
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('dimension', models.CharField(max_length=255)),
                ('residents', models.TextField()),
                ('url', models.URLField()),
                ('created', models.DateTimeField()),
            ],
            options={
                'db_table': 'locations',
            },
        ),
        migrations.CreateModel(
            name='Origins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
            ],
            options={
                'db_table': 'origins',
            },
        ),
        migrations.CreateModel(
            name='Characters2Episodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.characters')),
            ],
            options={
                'db_table': 'characters2episodes',
            },
        ),
        migrations.CreateModel(
            name='Episodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('air_date', models.DateTimeField()),
                ('episode', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('created', models.DateTimeField()),
                ('characters', models.ManyToManyField(related_name='characters_reverse', through='tables.Characters2Episodes', to='tables.characters')),
            ],
            options={
                'db_table': 'episodes',
            },
        ),
        migrations.AddField(
            model_name='characters2episodes',
            name='episodes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.episodes'),
        ),
        migrations.AddField(
            model_name='characters',
            name='episodes',
            field=models.ManyToManyField(related_name='episodes_reverse', through='tables.Characters2Episodes', to='tables.episodes'),
        ),
        migrations.AddField(
            model_name='characters',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.locations'),
        ),
        migrations.AddField(
            model_name='characters',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.origins'),
        ),
    ]
